### ISSUE TITLE
FluentD 0.14 ?

### ISSUE THREAD

**Issue by lukasmrtvy** [desdic/fluent-plugin-jsontcp#3]
Hello,
Is this plugin ready for FluentD 0.14 ? Thanks

**Comment by desdic** [comment]
We use it with td-agent version 2.3.5-0 and I think that is only fluentd 0.12 so I haven't tried

**Comment by lukasmrtvy** [comment]
FluentD 1.0 version:

```
2017-12-12 21:39:17 +0000 [warn]: #0 emit transaction failed: error_class=ArgumentError error="wrong number of arguments (given 3, expected 0)" location="/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/plugin/output.rb:956:in `block in handle_stream_simple'" tag="fluent.info"

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/plugin/output.rb:956:in `block in handle_stream_simple'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/event.rb:107:in `each'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/plugin/output.rb:955:in `handle_stream_simple'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/plugin/output.rb:841:in `execute_chunking'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/plugin/output.rb:771:in `emit_buffered'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/event_router.rb:159:in `emit_events'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/event_router.rb:96:in `emit_stream'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/event_router.rb:87:in `emit'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/engine.rb:207:in `block in log_event_loop'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/engine.rb:205:in `each'

  2017-12-12 21:39:17 +0000 [warn]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.0/lib/fluent/engine.rb:205:in `log_event_loop'

2017-12-12 21:39:17 +0000 [error]: #0 failed to emit fluentd's log event tag="fluent.info" event={"worker"=>0, "message"=>"fluentd worker is now running worker=0"} error_class=ArgumentError error="wrong number of arguments (given 3, expected 0)"
```

**Comment by desdic** [comment]
Sorry I haven't testet it against a 0.14 .. only 0.12
